# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  node: circleci/node@4.7
#making proper cicd routine
jobs:
  cicd-job:
    executor:
      name: node/default
    steps:
     - checkout 
     - run:
        name: Installing npm packages at server side
        command: cd server && npm install
     - run:
        name: Installing npm packages at client side
        command: cd.. && cd website-react && npm install
     - run:
        name: run tests
        command: npm run test
      - run:
        name: run linter
        command: npm run lint
      - run:
        name: deploy to service
        command: curl https://api.render.com/deploy/srv-cgir5s6bb6mnfcshkb30?key=gg_p-17Lb6g
      - run:
        name: deploy client side
#       command: 

workflows:
  example-workflow:
    jobs:
      - cicd-job
